### ISSUE TITLE
Deployment Help

### ISSUE THREAD

**Issue by cyber-bytezz** [sadikahmetaydin/doctor-appointment-website#1]
can you help me with the deployment>?

**Comment by sadikahmetaydin** [comment]
Sorry my mate I couldn't see your message. I can't help you that subject because I am learning that topic now . Thank for understanding.

**Comment by sadikahmetaydin** [comment]
Sorry my mate I couldn't see your message. I can't help you that subject because I am learning that topic now . Thank for understanding.
